##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/eom
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libjpeg-dev
    - liblcms2-dev
    - libmagickwand-dev
    - libmate-desktop-dev
    - libpeas-dev
    - librsvg2-dev
    - libstartup-notification0-dev
    - libxml2-dev
    - make
    - mate-common
    - shared-mime-info
    - x11proto-core-dev
    - yelp-tools
    - zlib1g-dev

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/mate-desktop/mate-common master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/mate-desktop/eom/raw/master/data/icons/16x16/apps/eom.png; fi
