##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:

before_scripts:
  - ./debrepo-install

build_scripts:
  - ./build-debs https://github.com/cafe-desktop/debian-packages devel eoc

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/cafe-desktop/eoc/raw/master/data/icons/16x16/apps/eoc.png; fi
